version: 2
jobs:
  build:
    docker:
      - image: openjdk:8-jdk
    steps:
      - checkout
      - run: git describe

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/