version: 2
jobs:
  tagging:
    docker:
      - image: openjdk:8-jdk-slim
    steps:
      - run: apt update && apt install jq git -y
      - checkout
      - run: git tag $(jq .date .version)
      - run: git tag $(jq .version .version)
      - run: git push --tags
  build:
    docker:
      - image: openjdk:8-jdk-slim
    steps:
      - run: apt update && apt install jq git -y
      - checkout
      - run: git describe

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - tagging:
          filters:
            branches:
              only: master
      - build:
          requires:
            - tagging 