name: Release 

on:
  repository_dispatch:
    types: [on_release]

jobs:
  update_:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          TAG="${{ github.event.client_payload.tag }}"
          echo $TAG > $TAG.release
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release-${{ github.event.client_payload.tag }}
          title: release ${{ github.event.client_payload.tag }} 
