name: Create a release pull-request
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create-release-pr
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: master
          head: develop
          token: ${{ secrets.GITHUB_TOKEN }}
          assign: true
